FROM python:3.6

RUN apt-get update && apt-get install -y sqlite3

RUN mkdir /app
WORKDIR /app
COPY *requirements.txt ./
RUN pip install -r requirements.txt -r dev_requirements.txt
COPY . /app

CMD make install-dev && make test